const array = [{
        firstName: 'Rasbin',
        lastName: '',
        title: 'Junior Developer',
        nationality: '',
        src: 'rasbin.jpg',
        alt: 'Rasbin',
        skills: ['HTML', 'CSS', 'Bootstrap', 'JavaScript', 'JQuery', 'React', 'PHP', 'MySQL'],
        whySofterDeveloper: 'Limitless opportunities of creation',
        longTermVision: 'IT Service Manager',
        motivatesMe: 'Books',
        favoriteQuote: 'Everything is possible',
        joinedOn: '01-12-2017'
    },

    {


        firstName: 'Aditya',
        lastName: 'Gyawali',
        Title: 'Trainee',
        nationality: 'Nepalese',
        src: 'aditya.jpg',
        alt: 'Aditya',
        skills: ['HTML', 'CSS', 'Bootstrap', 'JavaScript', 'JQuery', 'React'],
        whySofterDeveloper: 'Because you can work on any part of the world with the knowledge you have no language barrier n stuff',
        longTermVision: 'working on projects from home',
        motivatesMe: '€',
        favoriteQuote: 'It will take time, but it will happen',
        joinedOn: '22-1-2017'
    },

    {
        firstName: 'Sanjog',
        lastName: 'Shrestha',
        title: 'Junior Developer',
        nationality: 'Nepali',
        src: 'sanjog.jpg',
        alt: 'Sanjog',
        skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Redux'],
        whySofterDeveloper: 'Interest',
        longTermVision: 'Professional Software Developer',
        motivatesMe: '',
        favoriteQuote: '',
        joinedOn: '04.12.2017'
    }, {
        firstName: ' Tareq',
        lastName: 'Mahmud',
        title: 'Aspiring full stack developer',
        nationality: 'Bangladeshi',
        src: 'tareq.jpg',
        alt: 'Tareq',
        skills: ['Javascript', 'Reactjs', 'Reduxjs', 'Node.js', 'HTML5', 'CSS3', 'React-router', 'Bootstrap', 'Jquery'],
        whySofterDeveloper: 'passion for tech and business',
        longTermVision: 'become a fullstack developer',
        motivatesMe: 'solving everyday problems by using technologies',
        favoriteQuote: 'Do not go gentle into the good night',
        joinedOn: '31.01.2018'
    }, {
        firstName: 'Abdirahman',
        lastName: 'Ali',
        title: '',
        Nationality: 'Somali',
        src: 'abdirahman.jpg',
        alt: 'Abdirahman',
        skills: ['HTML', 'CSS', 'Javascript', 'Jqeury', 'react'],
        whySofterDeveloper: 'become an intelligent',
        longTermVision: 'to improve my skills further and become good enough ',
        motivatesMe: 'Always learning new stuff',
        favoriteQuote: '',
        joinedOn: '04/12/2017'
    }
    , {
        firstName: 'Olujuwon Ayoseyi',
        lastName: 'Alabi',
        title: 'Developer',
        nationality: 'Nigeria',
        src: 'olujuwon.jpg',
        alt: 'Olujuwon Ayoseyi',
        skills: ['Javascript', 'react.js', 'redux', 'Node.js', 'HTML5', 'CSS3', 'NPM', 'DOM', 'Regex', 'React-router', 'Bootstrap', 'Jquery'],
        whySofterDeveloper: 'Good skill to have',
        motivatesMe: 'Good food',
        longTermVision: 'Entrepreneur',
        favoriteQuote: `..I can't please you...`,
        joinedOn: '04-12-2017'


    },

    {
        firstName: 'Quoc Viet',
        lastName: 'Dang',
        title: 'Trainee',
        nationality: 'Vietnam',
        src: 'Viet.jpg',
        alt: 'Quoc Viet Dang',
        skills: ['HTML', 'CSS', 'JavaScript'],
        whySofterDeveloper: 'I love web development ',
        longTermVision: 'AI skills',
        motivatesMe: 'A stable job and fun in programming',
        favoriteQuote: 'No pain no gain',
        joinedOn: '04-2018'
    }, {
        firstName: 'Jaya Kumar',
        lastName: 'Bidari',
        title: 'Junior Developer',
        nationality: 'Nepalese',
        src: 'jaya.jpg',
        alt: 'I bet,Jaya is here',
        skills: [ 'HTML5', 'CSS3', 'JavaScript', 'React/Redux', 'MongoDB', 'Node.js'],
        whySofterDeveloper: 'To work with technologies that I can use to create things I wish',
        longTermVision: 'To be a senior developer',
        motivatesMe: 'Stories of success even after huge failures',
        favoriteQuote: 'If nothing changes,nothing changes.If you keep doing what youre doing, yourre going to keep getting what youre getting.You want change,make some (By Courtney C.Stevens,The Lies About Truth)',
        joinedOn: '16/04/2018'
    }, 


    {
        firstName: 'Christian',
        lastName: 'Hamamdjian',
        title: 'AD, Web Developer',
        nationality: 'Finnish',
        src: 'christian.jpg',
        alt: 'christian_hamamdjian',
        skills: ['Graphic design', 'HTML5', 'CSS3', 'JavaScript', 'Wordpress'],
        whySofterDeveloper: 'Because it has the potential to make the world a better place for my children.',
        longTermVision: 'Having an active role in changing things to the better for as many people as possible through participating in useful web and software development projects.',
        motivatesMe: 'Getting optimal results creating new unique interfaces.',
        favoriteQuote: `Don't give up`,
        joinedOn: '16/04/2018'
    }, {
        firstName: 'Pok Tik Benjamin',
        lastName: 'Leung',
        title: 'Trainee Web Developer',
        nationality: 'Hong Kong',
        src: 'ben.jpg',
        alt: 'poktikbenjamin.jpg',
        skills: ['JavaScript', 'CSS', 'HTML', 'Java', 'Business Development'],
        whySofterDeveloper: 'Software will be an important medium through which we interact with our thoughts, with each other, and with the world. To take part in the development of software is to take part in finding new perspectives of life, and perhaps, new meaning to live.',
        longTermVision: 'To find meaningful work in the digital realm until the robots take over.',
        motivatesMe: 'The remarkable dumbness of computers motivates me every morning to wake up and fix them.',
        favoriteQuote: 'Compare yourself to who you were yesterday, not who someone else is today.',
        joinedOn: '16.04.2018'
    }, {
        firstName: 'Nghia(Niko)',
        lastName: 'Le',
        title: 'Student',
        nationality: 'Vietnam',
        src: 'Niko.jpg',
        alt: 'Niko',
        skills: ['SASS', 'Javascript', 'React', 'Redux', 'Java', 'SQL'],
        whySofterDeveloper: 'Because I like coding',
        longTermVision: 'Become a Javascript full stack developer',
        motivatesMe: 'My mom',
        favoriteQuote: 'Just do it',
        joinedOn: '16.04.2018'
    }, {
        firstName: 'Hai',
        lastName: 'Truong',
        title: 'Trainee',
        nationality: 'Vietnam',
        src: 'Hai.jpg',
        Alt: 'happy ximbong',
        skills: ['Javascript', 'Java', 'Linear Algebra', 'Discrete Maths'],
        whySofterDeveloper: 'SW developer title is cool to have',
        longTermVision: 'Machine learning/ Data science',
        motivatesMe: '$$$',
        favoriteQuote: '',
        joinedOn: '16.04.2018'
    },
      
      {
          firstName: 'Andrew',
          lastName: 'Zheng',
          title: 'Backend-developer/DevOps',
          nationality: 'China',
          src: 'andrew.jpg',
          alt: 'Andrew Zheng',
          skills: ['HTML', 'CSS', 'JavaScript', 'Node.js', 'Python', 'Mongodb'],
          whySofterDeveloper: '',
          longTermVision: 'Full-stack developer',
          motivatesMe: 'FLOSS',
          favoriteQuote: 'He who never hopes, never despair!',
          joinedOn: '16.4.2018'
      },
      {
          firstName: 'Shora ',
          lastName: 'Jafar',
          title: 'Integrify Trainee',
          nationality: 'Iran',
          src: 'Shora.jpg',
          alt: 'shora',
          skills: ['HTML', 'CSS', 'JavaScript'],
          whySofterDeveloper: 'Enables me to build a decent and stable career',
          longTermVision: 'Becoming a full-stack developer',
          motivatesMe: 'Learning',
          favoriteQuote: '',
          joinedOn: '23/4/2018'
      },
      {
          firstName: 'Bojan ',
          lastName: 'Mitic',
          title: 'Junior Developer',
          nationality: 'Serbian',
          src: 'Bojan.jpg',
          alt: 'bojan',
          skills: ['HTML', 'CSS', 'Bootstrap', 'JQuery', 'JavaScript', 'Node.js', 'React', 'MongoDb'],
          whySofterDeveloper: 'I enjoy programming',
          longTermVision: 'Team lead',
          motivatesMe: 'Good food, sunny days...',
          favoriteQuote: 'We become what we imagine ourselves to be',
          joinedOn: '16.4.2018.'
      },
     

      {
          firstName: 'Aditya',
          lastName: 'Rana',
          title: 'Front-end Web developer Trainee',
          nationality: 'Indian',
          src: 'aditya.jpg',
          alt: 'Mypic',
          skills: ['HTML5', 'CSS3', 'SASS', 'Bootstrap', 'javascript', 'jquery'],
          whySofterDeveloper: 'I am passionate about the user interfaces',
          longTermVision: 'I want to be a successful full stack developer.',
          motivatesMe: 'New challenges',
          favoriteQuote: 'Life is your biggest enemy, to defeat it you have to live it.',
          joinedOn: '16.4.2018'
      },
      {
          firstName: 'Saidur ',
          lastName: 'Rahman',
          title: 'Trainee Web Developer',
          nationality: 'Bangladesh',
          src: 'saidur.jpg',
          alt: 'My Image',
          skills: ['HTML', 'CSS', 'Bootstrap', 'JavaScript', 'React', 'PHP', 'MySQL'],
          whySofterDeveloper: 'Its challenging and its allows to explore ones creativity',
          longTermVision: 'To become a Lead Software Developer',
          motivatesMe: 'New challenges and the passion to become successful',
          favoriteQuote: 'Lost in a sea of nameless spaces',
          joinedOn: '16th April 2018'
      },

      {
          firstName: 'Long ',
          lastName: 'Nghiem',
          title: 'Integrify Trainee',
          nationality: 'Vietnam',
          src: 'Long.jpg',
          Alt: 'long avatar',
          skills: ['JavaScript', 'Photoshop'],
          whySofterDeveloper: 'Technology motivates me',
          longTermVision: 'Full-stack web developer, then CIO',
          motivatesMe: 'Technology, Philosophy, Anime',
          favoriteQuote: 'The only thing I know is that I know nothing - Socrates',
          joinedOn: 'April 1, 2018'
      },
      {
          firstName: 'Rojak',
          lastName: 'Amtya',
          title: 'Trainee',
          nationality: 'Nepalese',
          src: 'rojak.jpg',
          alt: 'rojak',
          skills: ['HTML', 'CSS', 'JS'],
          whySofterDeveloper: 'Satisfaction probably',
          longTermVision: 'At least a Full-stack Developer',
          motivatesMe: 'technologies',
          favoriteQuote: 'They told me : "Do something you love everyday, so I do coding" :P',
          joinedOn: '16.04.2018'
      },

      {
          firstName: 'Yasir',
          lastName: 'Akbar',
          title: 'Web Developer Trainee',
          nationality: 'Pakistani/Finnish',
          src: 'Yasir.jpg',
          alt: 'Yasir',
          skills: ['Html', 'Css', 'Bootstrap', 'Wordpress', 'JavaScript', 'Jquery'],
          whySofterDeveloper: 'There is always something new to learn in coding and building websites and applications from scratch',
          longTermVision: 'to be a Full Stack Developer/ CEO of Software house',
          motivatesMe: 'Passionate about new coding techniques',
          favoriteQuote: 'what doesnt kill you makes you stronger ',
          joinedOn: '16.04.2018'
      },
      {
          firstName: 'Mouhssine',
          lastName: 'Idrissi Akhelij',
          title: 'Trainee at Integrify',
          nationality: 'Moroccan',
          src: 'mouhssine.jpg',
          alt: 'mouhssine',
          skills: ['CSS', 'HTML5', 'JavaScript'],
          whySofterDeveloper: 'because it is my passion',
          longTermVision: 'To be senior web developer',
          motivatesMe: 'Learning to use new technologies',
          favoriteQuote: 'Rien n est bon rien n est mauvais en soi tout depend de notre penseE',
          joinedOn: '16.04.2018'
      },

           {
          firstName: 'Abdi',
          lastName: 'Muleta',
          title: 'Developer and Partnerships Lead',
          nationality: 'Ethiopian',
          src: 'Abdi.jpg',
          alt: 'Abdi Muleta',
          skills: ['HTML5', 'CSS3', 'Javascript', 'Python', 'R', 'Photoshop'],
          whySofterDeveloper: 'To gain the best experiences and to get on top of my technical skills so I would be better equipped to run my own business.',
          longTermVision: 'Serial entrepreneur and investor',
          motivatesMe: 'Disrupting the status quo',
          favoriteQuote: 'If you want to succeed you should strike out on new paths, rather than travel the worn paths of accepted success.',
          joinedOn: '16.04.2018'
      },
      {
          firstName: 'Kushal',
          lastName: 'Atreya',
          title: 'Software Developer',
          nationality: 'Nepalese',
          src: 'kushal.jpg',
          alt: 'Kushal Atreya Image',
          skills: ['HTML5', 'CSS3', 'Javascript', 'React.js', 'Redux', 'Node.js', 'Mango DB'],
          whySofterDeveloper: 'Time and again suddenly my computer wouldnt work, and then I had to use command prompt to fix it, and I started exploring more about it and loved how powerful that dark blinking rectangle was, wow now I am far from that but still exploring, now I come under the definition of software developer and yes I want to make my living out of it. ',
          longTermVision: 'To be happy of what I do and to find things that makes me happy doing',
          motivatesMe: 'The release of dopamine when the program runs',
          favoriteQuote: 'One life, Live well',
          joinedOn: '01.08.2018'
      },
     
      {
          firstName: 'Anuj',
          lastName: 'Thapa',
          title: 'Mr',
          nationality: 'Nepali',
          src: 'Anuj.jpg',
          alt: 'Anuj profile picture',
          skills: ['HTML', 'CSS', 'JAVASCRIPT', 'C#'],
          whySofterDeveloper: 'Interested in software development and a good job',
          longTermVision: 'billionaire(at least millionaire)',
          motivatesMe: 'Successful people',
          favoriteQuote: 'Only I can change my life,No one can do it for me',
          joinedOn: 'Aug.2018'
      },
      {
          firstName: 'Richard',
          lastName: 'Jones',
          title: 'Mr',
          nationality: 'English',
          src: 'richard.jpg',
          Alt: 'richard photo',
          skills: ['HTML5', 'CCS', 'JavaScript', 'proofreading', 'copy editing', 'copywriting'],
          whySofterDeveloper: 'Its as good a job as any',
          longTermVision: 'Acute myopia',
          motivatesMe: 'Fiat currency',
          favoriteQuote: '"Beware of false knowledge; it is more dangerous than ignorance." George Bernard Shaw',
          joinedOn: 'Aug. 2018'
      },
      {
          firstName: 'Jolene',
          lastName: 'Hoang',
          title: 'Junior Developer',
          nationality: 'Vietnam',
          src: 'jolene.jpg',
          Alt: 'jolene photo',
          skills: ['HTML', 'CSS', 'JS'],
          whySofterDeveloper: 'is there something else more interesting?',
          longTermVision: 'startup founder',
          motivatesMe: 'waking up for a new challenge everyday',
          favoriteQuote: 'when you want something all the universe conspires in helping you to achieve it',
          joinedOn: 'August,2018'
      },
      {
          firstName: 'Biruk',
          lastName: 'Yemane',
          title: 'trainee',
          nationality: 'Ethiopian',
          src: 'biruk.jpg',
          Alt: 'biruks picture',
          skills: ['HTML5', 'JavaScript', 'CSS', 'SQL databases', 'Java Basics'],
          whySofterDeveloper: 'working on different projects and with different clients makes it enjoyable',
          longTermVision: 'Join a web development company',
          motivatesMe: 'satisfaction of applying my skills to solve problems',
          favoriteQuote: 'Just do it!',
          joinedOn: '1 Aug 2018'
      },
      
      {
          firstName: 'Elyas ',
          lastName: 'Addawe',
          title: 'Trainee',
          nationality: 'finnish',
          src: 'Elyas.jpg',
          Alt: 'my profile picture',
          skills: ['HTML', 'CSS', 'Javascript'],
          whySofterDeveloper: 'I always wanted to create something  ',
          longTermVision: 'Mix business with web developer skills',
          motivatesMe: '',
          favoriteQuote: `But it ain't how hard you hit,it's about how hard you can get hit and still keep moving forward `,
          joinedOn: '1/august/2018'
      },
    
 
      {
          firstName: 'Bernard',
          lastName: 'Kakengi',
          title: 'Software developer trainee',
          nationality: 'Tanzania',
          src: 'bernard.jpg',
          Alt: 'bernard Image',
          skills: ['HTML', 'CSS', 'JAVASCRIPT', 'RUBY', 'RUBY ON RAILS', 'SQL'],
          whySofterDeveloper: 'building and designing software for people in need and able to challenge myself',
          longTermVision: 'Working as a software developer and help other achieving their goals as developers',
          motivatesMe: 'seeing my code running and working as required motivates me.',
          favoriteQuote: 'Another coding day',
          joinedOn: '01/08/2018'
      },
 
  ]
  module.exports = { array };